/**
 * Verified ATS corrections — probed against live APIs (2026-06).
 * Applied when importing presets and when repairing the watchlist DB.
 */
export const ATS_OVERRIDES = {
    // ── Bay Area ──────────────────────────────────────────────────────────────
    'Netflix': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobs.netflix.com' },
    'Adobe': { ats_type: 'custom', ats_slug: null, career_url: 'https://adobe.com/careers' },
    'ServiceNow': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.servicenow.com' },
    'Zoom': { ats_type: 'custom', ats_slug: null, career_url: 'https://explore.zoom.us/en/careers' },
    'Palo Alto Networks': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobs.paloaltonetworks.com/en' },
    'Intuit': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.intuit.com' },
    'OpenAI': { ats_type: 'ashby', ats_slug: 'openai', career_url: 'https://openai.com/careers' },
    'Scale AI': { ats_type: 'custom', ats_slug: null, career_url: 'https://scale.com/careers' },
    'Cohere': { ats_type: 'ashby', ats_slug: 'cohere', career_url: 'https://cohere.com/careers' },
    'Hugging Face': { ats_type: 'custom', ats_slug: null, career_url: 'https://huggingface.co/jobs' },
    'Perplexity AI': { ats_type: 'custom', ats_slug: null, career_url: 'https://perplexity.ai/hub/careers' },
    'Weights & Biases': { ats_type: 'custom', ats_slug: null, career_url: 'https://wandb.ai/site/careers' },
    'Together AI': { ats_type: 'custom', ats_slug: null, career_url: 'https://together.ai/careers' },
    'Mistral AI': { ats_type: 'lever', ats_slug: 'mistral', career_url: 'https://mistral.ai/careers' },
    'Glean': { ats_type: 'custom', ats_slug: null, career_url: 'https://glean.com/careers' },
    'Groq': { ats_type: 'custom', ats_slug: null, career_url: 'https://groq.com/careers' },
    'Harvey AI': { ats_type: 'custom', ats_slug: null, career_url: 'https://harvey.ai/careers' },
    'Imbue': { ats_type: 'greenhouse', ats_slug: 'imbue', career_url: 'https://imbue.com/careers' },
    'Recursion Pharma': { ats_type: 'custom', ats_slug: null, career_url: 'https://recursion.com/careers' },
    'Snowflake': { ats_type: 'ashby', ats_slug: 'snowflake', career_url: 'https://careers.snowflake.com' },
    'dbt Labs': { ats_type: 'custom', ats_slug: null, career_url: 'https://getdbt.com/dbt-labs/careers' },
    'Airbyte': { ats_type: 'custom', ats_slug: null, career_url: 'https://airbyte.com/company/careers' },
    'HashiCorp': { ats_type: 'custom', ats_slug: null, career_url: 'https://hashicorp.com/careers' },
    'PlanetScale': { ats_type: 'greenhouse', ats_slug: 'planetscale', career_url: 'https://planetscale.com/careers' },
    'Cockroach Labs': { ats_type: 'custom', ats_slug: null, career_url: 'https://cockroachlabs.com/careers' },
    'CrowdStrike': { ats_type: 'custom', ats_slug: null, career_url: 'https://crowdstrike.com/careers' },
    'Stripe': { ats_type: 'custom', ats_slug: null, career_url: 'https://stripe.com/jobs' },
    'Plaid': { ats_type: 'custom', ats_slug: null, career_url: 'https://plaid.com/careers' },
    'DoorDash': { ats_type: 'greenhouse', ats_slug: 'doordashusa', career_url: 'https://careers.doordash.com' },
    'Uber': { ats_type: 'custom', ats_slug: null, career_url: 'https://uber.com/us/en/careers' },
    'Snap': { ats_type: 'custom', ats_slug: null, career_url: 'https://snap.com/en-US/jobs' },
    'Snap NYC': { ats_type: 'custom', ats_slug: null, career_url: 'https://snap.com/en-US/jobs' },
    'Eventbrite': { ats_type: 'custom', ats_slug: null, career_url: 'https://eventbrite.com/careers' },
    'Atlassian': { ats_type: 'custom', ats_slug: null, career_url: 'https://atlassian.com/company/careers' },
    'Notion': { ats_type: 'ashby', ats_slug: 'notion', career_url: 'https://notion.so/careers' },
    'Box': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobs.box.com' },
    'Zendesk': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.zendesk.com' },
    'Retool': { ats_type: 'custom', ats_slug: null, career_url: 'https://retool.com/careers' },
    'Veeva Systems': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.veeva.com' },
    'Veeva Systems NYC': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.veeva.com' },
    'Wiz': { ats_type: 'custom', ats_slug: null, career_url: 'https://wiz.io/careers' },
    'Snyk': { ats_type: 'custom', ats_slug: null, career_url: 'https://snyk.io/careers' },
    'Tesla': { ats_type: 'custom', ats_slug: null, career_url: 'https://tesla.com/careers' },
    'Waymo': { ats_type: 'greenhouse', ats_slug: 'waymo', career_url: 'https://waymo.com/careers' },
    'Cruise': { ats_type: 'custom', ats_slug: null, career_url: 'https://getcruise.com/careers' },
    'Joby Aviation': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobyaviation.com/careers' },
    'Impossible Foods': { ats_type: 'custom', ats_slug: null, career_url: 'https://impossible.com/pages/careers' },
    'Rippling': { ats_type: 'custom', ats_slug: null, career_url: 'https://rippling.com/company/careers' },
    'Aurora Innovation': { ats_type: 'greenhouse', ats_slug: 'aurorainnovation', career_url: 'https://aurora.tech/careers' },
    'Planet Labs': { ats_type: 'greenhouse', ats_slug: 'planetlabs', career_url: 'https://planet.com/careers' },

    // ── NYC ─────────────────────────────────────────────────────────────────────
    'Goldman Sachs': { ats_type: 'custom', ats_slug: null, career_url: 'https://goldmansachs.com/careers' },
    'Barclays': { ats_type: 'custom', ats_slug: null, career_url: 'https://barclays.com/careers' },
    'BlackRock': { ats_type: 'custom', ats_slug: null, career_url: 'https://blackrock.com/careers' },
    'BNY Mellon': { ats_type: 'custom', ats_slug: null, career_url: 'https://bnymellon.com/careers' },
    'American Express': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobs.americanexpress.com' },
    'Capital One': { ats_type: 'custom', ats_slug: null, career_url: 'https://capitalonecareers.com' },
    'Two Sigma': { ats_type: 'custom', ats_slug: null, career_url: 'https://twosigma.com/careers' },
    'Hudson River Trading': { ats_type: 'greenhouse', ats_slug: 'hrttalentcommunity', career_url: 'https://hudson-trading.com/careers' },
    "Moody's Analytics": { ats_type: 'custom', ats_slug: null, career_url: 'https://moodys.com/careers' },
    'Bloomberg': { ats_type: 'custom', ats_slug: null, career_url: 'https://bloomberg.com/careers' },
    'S&P Global': { ats_type: 'custom', ats_slug: null, career_url: 'https://spglobal.com/en/careers' },
    'FactSet': { ats_type: 'custom', ats_slug: null, career_url: 'https://factset.com/careers' },
    'Nasdaq': { ats_type: 'custom', ats_slug: null, career_url: 'https://nasdaq.com/about/careers' },
    'Verisk Analytics': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.verisk.com' },
    'TransUnion': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.transunion.com' },
    'IBM': { ats_type: 'custom', ats_slug: null, career_url: 'https://ibm.com/employment' },
    'Spotify': { ats_type: 'custom', ats_slug: null, career_url: 'https://lifeatspotify.com' },
    'Etsy': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobs.etsy.com' },
    'Datadog': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.datadoghq.com' },
    'Shutterstock': { ats_type: 'custom', ats_slug: null, career_url: 'https://shutterstock.com/careers' },
    'Nielsen': { ats_type: 'custom', ats_slug: null, career_url: 'https://nielseniq.com/careers' },
    'ZS Associates': { ats_type: 'custom', ats_slug: null, career_url: 'https://zs.com/careers' },
    'Warby Parker': { ats_type: 'custom', ats_slug: null, career_url: 'https://warbyparker.com/careers' },
    'Oscar Health': { ats_type: 'custom', ats_slug: null, career_url: 'https://hioscar.com/careers' },
    'Noom': { ats_type: 'custom', ats_slug: null, career_url: 'https://noom.com/careers' },
    'Compass': { ats_type: 'custom', ats_slug: null, career_url: 'https://compass.com/careers' },
    'Medidata': { ats_type: 'custom', ats_slug: null, career_url: 'https://medidata.com/careers' },
    'IQVIA': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobs.iqvia.com' },
    'Booz Allen Hamilton': { ats_type: 'custom', ats_slug: null, career_url: 'https://careers.boozallen.com' },
    'Marsh McLennan': { ats_type: 'custom', ats_slug: null, career_url: 'https://mmc.com/careers' },
    'MetLife': { ats_type: 'custom', ats_slug: null, career_url: 'https://jobs.metlife.com' },
    'Prudential Financial': { ats_type: 'custom', ats_slug: null, career_url: 'https://prudential.com/links/about/careers' },

    // ── Seattle ─────────────────────────────────────────────────────────────────
    'Expedia Group': { ats_type: 'custom', ats_slug: null, career_url: 'https://lifeatexpedia.com' },
    'REI': { ats_type: 'custom', ats_slug: null, career_url: 'https://rei.com/careers' },
    'DocuSign': { ats_type: 'custom', ats_slug: null, career_url: 'https://docusign.com/company/careers' },
    'Avalara': { ats_type: 'custom', ats_slug: null, career_url: 'https://avalara.com/us/en/about/careers' },
    'WatchGuard Technologies': { ats_type: 'custom', ats_slug: null, career_url: 'https://watchguard.com/wgrd-about/careers' },
    'F5 Networks': { ats_type: 'custom', ats_slug: null, career_url: 'https://f5.com/company/careers' },
    'Allen Institute for AI': { ats_type: 'greenhouse', ats_slug: 'thealleninstitute', career_url: 'https://allenai.org/careers' },
    'Vast Data': { ats_type: 'custom', ats_slug: null, career_url: 'https://vastdata.com/careers' },
    'SparkCognition': { ats_type: 'custom', ats_slug: null, career_url: 'https://sparkcognition.com/careers' },
    'Adaptive Biotechnologies': { ats_type: 'custom', ats_slug: null, career_url: 'https://adaptivebiotech.com/careers' },
    'Qumulo': { ats_type: 'custom', ats_slug: null, career_url: 'https://qumulo.com/careers' },
    'Remitly': { ats_type: 'custom', ats_slug: null, career_url: 'https://remitly.com/us/en/home/careers' },
    'Redfin': { ats_type: 'custom', ats_slug: null, career_url: 'https://redfin.com/about/jobs' },
    'Zillow': { ats_type: 'custom', ats_slug: null, career_url: 'https://zillow.com/careers' },
    'Rover.com': { ats_type: 'custom', ats_slug: null, career_url: 'https://rover.com/careers' },
    'Chewy': { ats_type: 'custom', ats_slug: null, career_url: 'https://chewy.com/jobs' },
    'Convoy': { ats_type: 'custom', ats_slug: null, career_url: 'https://convoy.com/careers' },
    'Shippo': { ats_type: 'custom', ats_slug: null, career_url: 'https://goshippo.com/careers' },
    'Porch Group': { ats_type: 'custom', ats_slug: null, career_url: 'https://porchgroup.com/careers' },
    'Accolade': { ats_type: 'custom', ats_slug: null, career_url: 'https://accoladecare.com/about/careers' },
    'Limeade': { ats_type: 'custom', ats_slug: null, career_url: 'https://limeade.com/about/careers' },
    'Fred Hutchinson Cancer Center': { ats_type: 'custom', ats_slug: null, career_url: 'https://fredhutch.org/careers' },
    'Sana Biotechnology': { ats_type: 'custom', ats_slug: null, career_url: 'https://sana.com/careers' },
    'Apixio': { ats_type: 'custom', ats_slug: null, career_url: 'https://apixio.com/company/careers' },
    'Outreach': { ats_type: 'custom', ats_slug: null, career_url: 'https://outreach.io/company/careers' },
    'Highspot': { ats_type: 'custom', ats_slug: null, career_url: 'https://highspot.com/careers' },
    'Icertis': { ats_type: 'custom', ats_slug: null, career_url: 'https://icertis.com/company/careers' },
    'Auth0 (Okta)': { ats_type: 'custom', ats_slug: null, career_url: 'https://okta.com/company/careers' },
    'WP Engine': { ats_type: 'custom', ats_slug: null, career_url: 'https://wpengine.com/careers' },
    'Hiya': { ats_type: 'ashby', ats_slug: 'hiya', career_url: 'https://hiya.com/careers' },
    'Formant': { ats_type: 'custom', ats_slug: null, career_url: 'https://formant.io/careers' },
    'Saildrone': { ats_type: 'custom', ats_slug: null, career_url: 'https://saildrone.com/careers' },
    'Jobber': { ats_type: 'custom', ats_slug: null, career_url: 'https://getjobber.com/careers' },
    'Boundless Immigration': { ats_type: 'custom', ats_slug: null, career_url: 'https://boundless.com/about/careers' },
    'Limelight Networks': { ats_type: 'custom', ats_slug: null, career_url: 'https://limelight.com/careers' },
    'WellSky': { ats_type: 'custom', ats_slug: null, career_url: 'https://wellsky.com/careers' },
    'Rad Power Bikes': { ats_type: 'custom', ats_slug: null, career_url: 'https://radpowerbikes.com/pages/careers' },
    'MedBridge': { ats_type: 'custom', ats_slug: null, career_url: 'https://medbridgeeducation.com/careers' },
    'Algorithmia (DataRobot)': { ats_type: 'custom', ats_slug: null, career_url: 'https://datarobot.com/careers' },
    'Fareportal': { ats_type: 'custom', ats_slug: null, career_url: 'https://fareportal.com/careers' },
    'Concord Technologies': { ats_type: 'custom', ats_slug: null, career_url: 'https://concordfax.com/careers' },
    'Zulily': { ats_type: 'custom', ats_slug: null, career_url: 'https://zulily.com/careers' },
    'Athira Pharma': { ats_type: 'custom', ats_slug: null, career_url: 'https://athirapharma.com/about/careers' },
    'Omeros': { ats_type: 'custom', ats_slug: null, career_url: 'https://omeros.com/about-us/careers' },
    'Nautilus Biotechnology': { ats_type: 'custom', ats_slug: null, career_url: 'https://nautilustechnologies.com/careers' },
    'Kyowa Kirin': { ats_type: 'custom', ats_slug: null, career_url: 'https://kyowakirin.com/careers' },
    'BioAtla': { ats_type: 'custom', ats_slug: null, career_url: 'https://bioatla.com/careers' },
    'Nuvation Bio': { ats_type: 'custom', ats_slug: null, career_url: 'https://nuvationbio.com/careers' },
};

/** Merge preset company with verified override if one exists. */
export function applyAtsOverride(company) {
    const override = ATS_OVERRIDES[company.name];
    if (!override) return company;
    return { ...company, ...override };
}

export function applyAtsOverrides(companies) {
    return companies.map(applyAtsOverride);
}
