/**
 * Companies discovered from Web Data Commons' schema.org JobPosting extract
 * (https://webdatacommons.org/structureddata/) that resolve to a supported
 * ATS. Generated by scripts/discover-companies-from-wdc.js — do not hand-edit;
 * re-run the script to refresh.
 *
 * This starting file is an empty placeholder so the app runs before the
 * script has ever been executed. Run `node scripts/discover-companies-from-wdc.js`
 * to populate it.
 */

export const WDC_DISCOVERED_COMPANIES = [
];

export const WDC_DISCOVERED_PRESET = {
    id: 'wdc-discovered',
    label: `WDC Discovered (${WDC_DISCOVERED_COMPANIES.length})`,
    description: 'Companies found via Web Data Commons\' schema.org job-posting data, verified against a supported ATS.',
    companies: WDC_DISCOVERED_COMPANIES,
};
